Check prebuild dictionary exists

diff --git a/dict/auto/Makefile.am b/dict/auto/Makefile.am
--- a/dict/auto/Makefile.am
+++ b/dict/auto/Makefile.am
@@ -17,6 +17,9 @@ auto.dat:
 
 auto.db: auto.dat wikipedia.dat*
 	if [ -f wikipedia.dat.skip ]; then \
+		if [ ! -f $@ ]; then \
+			echo -e '\e[1;31m.skip exists. However $@ is not found\e[m' 1>&2; exit 5;\
+		fi; \
 		echo -e '\e[1;31mSkip build of $@ \e[m' 1>&2 :;\
 	elif [ -f wikipedia.dat.xz ]; then \
 		bash -c 'LANG=C sort auto.dat <(xzcat wikipedia.dat.xz) | @MAKE_DB_COMMAND@ $@ -append \|;' ; \
diff --git a/dict/distsim/Makefile.am b/dict/distsim/Makefile.am
--- a/dict/distsim/Makefile.am
+++ b/dict/distsim/Makefile.am
@@ -13,6 +13,9 @@ endif
 
 mi.db: mi.dat*
 	if [ -f mi.dat.skip ]; then \
+		if [ ! -f $@ ]; then \
+			echo -e '\e[1;31m.skip exists. However $@ is not found\e[m' 1>&2; exit 5;\
+		fi; \
 		echo -e '\e[1;31mSkip build of $@ \e[m' 1>&2 :;\
 	elif [ -f mi.dat.xz ]; then \
 		xzcat mi.dat.xz | @MAKE_DB_COMMAND@ $@ -z; \
@@ -24,6 +27,9 @@ mi.db: mi.dat*
 
 sim.db: sim.dat*
 	if [ -f sim.dat.skip ]; then \
+		if [ ! -f $@ ]; then \
+			echo -e '\e[1;31m.skip exists. However $@ is not found\e[m' 1>&2; exit 5;\
+		fi; \
 		echo -e '\e[1;31mSkip build of $@ \e[m' 1>&2 :;\
 	elif [ -f sim.dat.xz ]; then \
 		xzcat sim.dat.xz | @MAKE_DB_COMMAND@ $@; \
diff --git a/dict/ebcf/Makefile.am b/dict/ebcf/Makefile.am
--- a/dict/ebcf/Makefile.am
+++ b/dict/ebcf/Makefile.am
@@ -52,6 +52,9 @@ IPALN_DIR   = /share/dict/ipal_noun_31/3.1/data
 
 cf.dat: cf.knpdict*
 	if [ -f cf.knpdict.skip ]; then \
+		if [ ! -f $@ ]; then \
+			echo -e '\e[1;31m.skip exists. However $@ is not found\e[m' 1>&2; exit 5;\
+		fi; \
 		echo -e '\e[1;31mSkip build of $@ \e[m' 1>&2 :;\
 	elif [ -f cf.knpdict.xz ]; then \
 		ulimit -Ss unlimited && xzcat cf.knpdict.xz |  @CF_COMMAND@ cf.idx cf.dat; \
@@ -69,6 +72,9 @@ cf.db: cf.dat
 
 noun.dat: noun.knpdict*
 	if [ -f noun.knpdict.skip ]; then \
+		if [ ! -f $@ ]; then \
+			echo -e '\e[1;31m.skip exists. However $@ is not found\e[m' 1>&2; exit 5;\
+		fi; \
 		echo -e '\e[1;31mSkip build of $@ \e[m' 1>&2 :;\
 	elif [ -f noun.knpdict.xz ]; then \
 		ulimit -Ss unlimited && xzcat noun.knpdict.xz | @CF_COMMAND@ noun.idx noun.dat; \
@@ -94,6 +100,9 @@ adverb.db: adverb.prob
 
 case.db: case.prob*
 	if [ -f case.prob.skip ]; then \
+		if [ ! -f $@ ]; then \
+			echo -e '\e[1;31m.skip exists. However $@ is not found\e[m' 1>&2; exit 5;\
+		fi; \
 		echo -e '\e[1;31mSkip build of $@ \e[m' 1>&2 :;\
 	elif [ -f case.prob.xz ]; then \
 		xzcat case.prob.xz | @MAKE_DB_COMMAND@ $@; \
@@ -106,6 +115,9 @@ case.db: case.prob*
 
 cfcase.db: cfcase.prob*
 	if [ -f cfcase.prob.skip ]; then \
+		if [ ! -f $@ ]; then \
+			echo -e '\e[1;31m.skip exists. However $@ is not found\e[m' 1>&2; exit 5;\
+		fi; \
 		echo -e '\e[1;31mSkip build of $@ \e[m' 1>&2 :;\
 	elif [ -f cfcase.prob.xz ]; then \
 		xzcat cfcase.prob.xz | @MAKE_DB_COMMAND@ $@; \
@@ -118,6 +130,9 @@ cfcase.db: cfcase.prob*
 
 cfp.db: cfp.prob*
 	if [ -f cfp.prob.skip ]; then \
+		if [ ! -f $@ ]; then \
+			echo -e '\e[1;31m.skip exists. However $@ is not found\e[m' 1>&2; exit 5;\
+		fi; \
 		echo -e '\e[1;31mSkip build of $@ \e[m' 1>&2 :;\
 	elif [ -f cfp.prob.xz ]; then \
 		xzcat cfp.prob.xz | @MAKE_DB_COMMAND@ $@; \
@@ -156,6 +171,9 @@ prob: $(PROBCASE_DBS)
 
 mrph2id.db: mrph2id.dat*
 	if [ -f mrph2id.dat.skip ]; then \
+		if [ ! -f $@ ]; then \
+			echo -e '\e[1;31m.skip exists. However $@ is not found\e[m' 1>&2; exit 5;\
+		fi; \
 		echo -e '\e[1;31mSkip build of $@ \e[m' 1>&2 :;\
 	elif [ -f mrph2id.dat.xz ]; then \
 		xzcat mrph2id.dat.xz | @MAKE_DB_COMMAND@ $@; \
@@ -167,6 +185,9 @@ mrph2id.db: mrph2id.dat*
 
 case_soto.txt: mrph2id.dat* case_soto_words.txt case_soto_conv.py
 	if [ -f mrph2id.dat.skip ];then \
+		if [ ! -f $@ ]; then \
+			echo -e '\e[1;31m.skip exists. However $@ is not found\e[m' 1>&2; exit 5;\
+		fi; \
 		echo -e '\e[1;31mSkip build of $@ \e[m' 1>&2 :;\
 	elif [ -f mrph2id.dat.xz ];then \
 	    bash -c 'python case_soto_conv.py -s case_soto_words.txt -m <(xzcat mrph2id.dat.xz) -o $@.tmp && mv $@.tmp $@ '; \
